# Generated by Django 4.0.5 on 2022-06-24 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_maincategory_options_alter_category_main_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Parent', to='category.maincategory'),
        ),
    ]
