# Generated by Django 4.0.5 on 2022-06-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_remove_maincategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='name',
            field=models.CharField(choices=[('MEN', 'MEN'), ('WOMEN', 'WOMEN'), ('KIDS', 'KIDS')], default='MEN', max_length=20),
        ),
    ]
